defaults: &defaults
  pomotime: 24
  cool:
    saweet: nested settings
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults
